# This workflow is for building docker image
name: Run maven test on push

on:
  push:
    branches: [ main ]

jobs:
 build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag Spaytask:$(date +%s
