name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

 docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker image
        run: docker build -f Dockerfile -t springbootast101:$(date +%s)
